[theme]
base = "dark"
primaryColor = "#ef2945"
backgroundColor = "#0c0e11"
secondaryBackgroundColor = "#20242a"
textColor = "#f6f7f9"
font = "sans serif"

[server]
maxUploadSize = 2
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
